name: Check PR Title Format

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr-title-format:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: *
          helpMessage: "TBD"
